// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import Notification from "@stimulus-components/notification";
import AutoSubmit from "@stimulus-components/auto-submit";

import TurboModalController from "./turbo_modal_controller";

application.register("turbo-modal", TurboModalController);
application.register("notification", Notification);
application.register("auto-submit", AutoSubmit);
