services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - rra-database:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  pgdata:
  rra-database:
